language: java

# whitelist
branches:
 only:
  - master
 
jdk:
 - oraclejdk8

before_install:
 - chmod +x ./org.eclipse.richbeans.releng/build/commit-msg.sh
 - bash ./org.eclipse.richbeans.releng/build/commit-msg.sh
 
mvn compile
